version: '3.8'
services:
  db:
    image: postgres:15
    container_name: bank-postgres
    restart: always
    environment:
      POSTGRES_DB: bank_rest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.3
    container_name: bank-redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    image: bank-rest-app:latest
    container_name: bank-rest-app
    depends_on:
      - db
      - redis
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bank_rest
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_LIQUIBASE_ENABLED: 'true'
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  db_data: