spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_rest
    username: postgres
    password: root
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
  cache:
    type: redis

server:
  port: 8080
logging:
  level:
    org.springframework.security: DEBUG

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html